[CI] Enable build and test for XPU

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -57,6 +57,12 @@ jobs:
           echo "Detected ROCm image"
           rocminfo || echo "rocminfo not found"
 
+      - name: Run XPU command
+        if: startsWith(matrix.image, 'intel')
+        run: |
+          echo "Detected XPU image"
+          xpu-smi discovery || echo "xpu-smi not found"
+
       - name: Check out code
         uses: actions/checkout@v6
 
@@ -134,10 +140,12 @@ jobs:
           export CXX=clang++-20
           mkdir -p /tmp/$USER
           cd /tmp/$USER
-          uv pip uninstall triton pytorch-triton || true
+          uv pip uninstall triton pytorch-triton triton-xpu || true
           rm -rf triton/ || true
           if [[ "${{ matrix.backend }}" == "tileir" ]]; then
             git clone --recursive -b main https://github.com/triton-lang/Triton-to-tile-IR.git triton
+          elif [[ "${{ matrix.alias }}" == *xpu* ]]; then
+            git clone https://github.com/intel/intel-xpu-backend-for-triton.git triton
           else
             git clone https://github.com/triton-lang/triton.git triton
             if [[ "${{ matrix.python-version }}" == "3.14" ]]; then
